config/routes.rb
Rails.application.routes.draw do
  get 'user_stories/index'
  resources :user_stories

   root 'user_stories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user_story
end

app/models/user_story.rb
class UserStory < ActiveRecord::Base
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  def index
    @user_stories = UserStory.all
  end

  def show
    @user_story = UserStory.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stories_helper.rb
module UserStoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TinyHouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_stories/index.html.erb
<h1>YEH! Tiny Houses</h1>

<% @user_stories.each do |us| %>
  <%= link_to us.name, user_story_path(us.id) %>
<% end %>

app/views/user_stories/show.html.erb
<h1><%= @user_story.name %></h1>
<% @user_story.categories.each do |cat| %>
  <%= cat.name %>
<% end %>